version: 0.0
os: linux
files:
  - source: /target/web-calculator.war
    destination: /opt/tomcat/webapps/

hooks:
  # BlockTraffic:
  #   - location: scripts/block_traffic.sh
  #     timeout: 120  # Set a lower timeout, e.g., 120 seconds
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
    - location: scripts/remove_old_war.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
